### ISSUE TITLE
exception when trying to contact api

### ISSUE THREAD

**Issue by stefanfoulis** [translations-com/globallink-connect-api-python#2]
Maybe the ``.wsdl`` files in this repo are not up to date or there is a missing Class in the python implementation?

```python
from glexchange.GLExchange import GLExchange
from glexchange.model.ProjectDirectorConfig import ProjectDirectorConfig

config = ProjectDirectorConfig()
config.url = 'http://gl-pilot4.translations.com/PD'
config.username = '<MY USERNAME>'
config.password = '<MY PASSWORD>'
config.userAgent = 'myclient'
xchange = GLExchange(config)
```

```python traceback
Traceback (most recent call last):
  File "mygce.py", line 14, in <module>
    xchange = GLExchange(config)
  File "/app/globallink-connect-api-python/glexchange/GLExchange.py", line 30, in __init__
    self.setConnectionConfig(config)
  File "/app/globallink-connect-api-python/glexchange/GLExchange.py", line 63, in setConnectionConfig
    self._workflowService = Client("file:///"+path+"/wsdl/WorkflowService_4130.wsdl")
  File "/usr/local/lib/python2.7/site-packages/suds/client.py", line 119, in __init__
    sd = ServiceDefinition(self.wsdl, s)
  File "/usr/local/lib/python2.7/site-packages/suds/servicedefinition.py", line 58, in __init__
    self.paramtypes()
  File "/usr/local/lib/python2.7/site-packages/suds/servicedefinition.py", line 137, in paramtypes
    item = (pd[1], pd[1].resolve())
  File "/usr/local/lib/python2.7/site-packages/suds/xsd/sxbasic.py", line 63, in resolve
    raise TypeNotFound(qref)
suds.TypeNotFound: Type not found: '(WorkflowRequestTicket, http://dto.model.projectdirector.gs4tr.org/xsd, )'
```

```
backports.shutil-get-terminal-size==1.0.0
decorator==4.0.10
enum34==1.1.6
ipdb==0.10.1
ipython==5.1.0
ipython-genutils==0.1.0
pathlib2==2.1.0
pexpect==4.2.1
pickleshare==0.7.4
prompt-toolkit==1.0.9
ptyprocess==0.5.1
Pygments==2.1.3
simplegeneric==0.8.1
six==1.10.0
suds==0.4
traitlets==4.3.1
virtualenv==15.0.3
wcwidth==0.1.7
```

**Comment by stefanfoulis** [comment]
Thanks for the updated code. Now I am getting this error:

```python traceback
Traceback (most recent call last):
  File "mygce.py", line 14, in <module>
    xchange = GLExchange(config)
  File "/app/globallink-connect-api-python/glexchange/GLExchange.py", line 30, in __init__
    self.setConnectionConfig(config)
  File "/app/globallink-connect-api-python/glexchange/GLExchange.py", line 52, in setConnectionConfig
    self._projectService = Client("file:///"+path+"/wsdl/ProjectService_4130.wsdl")
  File "/usr/local/lib/python2.7/site-packages/suds/client.py", line 112, in __init__
    self.wsdl = reader.open(url)
  File "/usr/local/lib/python2.7/site-packages/suds/reader.py", line 152, in open
    d = self.fn(url, self.options)
  File "/usr/local/lib/python2.7/site-packages/suds/wsdl.py", line 159, in __init__
    self.build_schema()
  File "/usr/local/lib/python2.7/site-packages/suds/wsdl.py", line 220, in build_schema
    self.schema = container.load(self.options)
  File "/usr/local/lib/python2.7/site-packages/suds/xsd/schema.py", line 93, in load
    child.open_imports(options)
  File "/usr/local/lib/python2.7/site-packages/suds/xsd/schema.py", line 305, in open_imports
    imported = imp.open(options)
  File "/usr/local/lib/python2.7/site-packages/suds/xsd/sxbasic.py", line 542, in open
    result = self.download(options)
  File "/usr/local/lib/python2.7/site-packages/suds/xsd/sxbasic.py", line 560, in download
    d = reader.open(url)
  File "/usr/local/lib/python2.7/site-packages/suds/reader.py", line 79, in open
    d = self.download(url)
  File "/usr/local/lib/python2.7/site-packages/suds/reader.py", line 95, in download
    fp = self.options.transport.open(Request(url))
  File "/usr/local/lib/python2.7/site-packages/suds/transport/https.py", line 60, in open
    return  HttpTransport.open(self, request)
  File "/usr/local/lib/python2.7/site-packages/suds/transport/http.py", line 62, in open
    return self.u2open(u2request)
  File "/usr/local/lib/python2.7/site-packages/suds/transport/http.py", line 118, in u2open
    return url.open(u2request, timeout=tm)
  File "/usr/local/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/local/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/local/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python2.7/urllib2.py", line 1336, in file_open
    return self.open_local_file(req)
  File "/usr/local/lib/python2.7/urllib2.py", line 1376, in open_local_file
    raise URLError(msg)
urllib2.URLError: <urlopen error [Errno 2] No such file or directory: '/globallink-connect-api-python/glexch
ange/wsdl/types.xsd'>
```

The url passed into suds in "/app/globallink-connect-api-python/glexchange/GLExchange.py", line 52 is ``file:////app/globallink-connect-api-python/glexchange/wsdl/ProjectService_4130.wsdl`` while the url generated by suds in "/usr/local/lib/python2.7/site-packages/suds/reader.py", line 79, in ``d = self.download(url)`` for the relative addition of types.xsd is ``file://app/globallink-connect-api-python/glexchange/wsdl/types.xsd``.
I'm not sure what is going wrong here.
