### ISSUE TITLE
exception when trying to retrieve all or specific project

### ISSUE THREAD

**Issue by Chive** [translations-com/globallink-connect-api-python#3]
Hi there

picking up where @stefanfoulis left off a while ago. I'm now getting an error whilst trying to retrieve either one or multiple projects from the exchange.

I'm using the latest version (as of writing this issue) directly from this repo on a box running Linux.

## Script

```python
# script.py

import os

from glexchange.GLExchange import GLExchange
from glexchange.model.ProjectDirectorConfig import ProjectDirectorConfig


env = os.environ.get

config = ProjectDirectorConfig()
config.url = env('TP_URL')
config.username = env('TP_USERNAME')
config.password = env('TP_PASSWORD')
config.userAgent = env('TP_USERAGENT')

project_id = env('TP_PROJECT_ID')
exchange = GLExchange(config)

# all good until here, now either of the following two commands fail in the same error

exchange.getProjects(False)
exchange.getProject(project_id)
```

## Error

```python
# python script.py 

No handlers could be found for logger "suds.client"
Traceback (most recent call last):
  File "script.py", line 18, in <module>
    xchange.getProjects(False)
  File "/app/globallink-connect-api-python/glexchange/GLExchange.py", line 331, in getProjects
    response = self._projectService.service.getUserProjects(includeSubProjects)
  File "/usr/local/lib/python2.7/site-packages/suds/client.py", line 542, in __call__
    return client.invoke(args, kwargs)
  File "/usr/local/lib/python2.7/site-packages/suds/client.py", line 602, in invoke
    result = self.send(soapenv)
  File "/usr/local/lib/python2.7/site-packages/suds/client.py", line 649, in send
    result = self.failed(binding, e)
  File "/usr/local/lib/python2.7/site-packages/suds/client.py", line 702, in failed
    r, p = binding.get_fault(reply)
  File "/usr/local/lib/python2.7/site-packages/suds/bindings/binding.py", line 258, in get_fault
    faultroot = sax.parse(string=reply)
  File "/usr/local/lib/python2.7/site-packages/suds/sax/parser.py", line 136, in parse
    sax.parse(source)
  File "/usr/local/lib/python2.7/xml/sax/expatreader.py", line 110, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/usr/local/lib/python2.7/xml/sax/xmlreader.py", line 123, in parse
    self.feed(buffer)
  File "/usr/local/lib/python2.7/xml/sax/expatreader.py", line 217, in feed
    self._err_handler.fatalError(exc)
  File "/usr/local/lib/python2.7/xml/sax/handler.py", line 38, in fatalError
    raise exception
xml.sax._exceptions.SAXParseException: <unknown>:1:0: syntax error
```

Any pointers? Thanks!

**Comment by masanzsa** [comment]
Hi @Chive 

The problem is that you are missing some dependencies: suds, soap and datetime.
Please download the library using pypi so you can feed from our latest version:
`pip install glexchange` the pypi repo will resolve the necessary dependencies. 
Please reopen the issue may you have any other problem.
Thanks!

Mariano Sanz
